### ISSUE TITLE
Password with '$'

### ISSUE THREAD

**Issue by yokall** [IAL32/WSL2-Create-Distro#1]
When setting a password for the user during the pipeline I entered a password that contained the `$` symbol but once inside the new wsl instance the password didn't work.  I made another wsl instance with a simple password and it worked fine.  Is there any way to escape `$` in the password?

**Comment by IAL32** [comment]
Hi @yokall !

For PowerShell, the `$` sign is a special character used for replacing variables. If you'd like to use the `$` sign as it is, you would have to escape it using the dedicated ``` ` ``` (backtick) symbol:

```
ROOT_PASSWORD: random_yet`$effective
```

Hope this helps!

**Comment by yokall** [comment]
Thanks for the reply @IAL32

If I had studied the error message more closely I'd have seen that it was saying

```
/bin/bash: $: command not found
``` 

So the `$` needs escaped in bash with `\`.  

```
ROOT_PASSWORD: random_yet\$effective
```

Thank you for putting me down the right path
