### ISSUE TITLE
Question of two WSL running NGINX

### ISSUE THREAD

**Issue by luisee** [IAL32/WSL2-Create-Distro#2]
Hello, thanks the script has helped me a lot. I have a query, If I have two WSL active and each one I have NGINX running on port 80, they conflict when accessing from chrome to localhost (chrome windows) and if so, how can I avoid that conflict? Thanks for the reply.

**Comment by IAL32** [comment]
Hi @luisee ! I'm very happy that this script has helped you!

Unfortunately, the only way to avoid such conflict is to change one of the two ports

**Comment by IAL32** [comment]
Closing issue, as this does not really relate to the overall functionality of the script.
